# Generated by Django 4.2.5 on 2023-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainusercentral',
            name='UniqueID',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='mainusercentral',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
