# Generated by Django 4.2.5 on 2023-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMan', '0002_mainusercentral_uniqueid_alter_mainusercentral_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusercentral',
            name='UniqueID',
            field=models.CharField(default='', null=True),
        ),
    ]
