# Generated by Django 4.2.5 on 2023-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMan', '0003_alter_mainusercentral_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusercentral',
            name='bucket_url',
            field=models.URLField(null=True),
        ),
    ]
