# Generated by Django 4.2.5 on 2023-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMan', '0004_alter_mainusercentral_bucket_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusercentral',
            name='UniqueID',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
